### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#109]
Crash Happens "POSSIBLE" Upon Save.
Crash Report In Your PC: (location)

C:\Users\Amentrix\Desktop\Minecraft Server\Minecraft\.\crash-reports\crash-2017-03-28_21.50.04-server.txt

**Comment by EvilPeanut** [comment]
Investigating now

**Comment by EvilPeanut** [comment]
I have just scanned the Amentrix world and found 3 corrupt chunks. I will now remove them, scan the world again to ensure it's fixed, check FlatLand for good measure and then report back 😄

**Comment by EvilPeanut** [comment]
Issues and corruption in the Amentrix world are confirmed fixed 😋

**Comment by EvilPeanut** [comment]
The scan of Flatland is complete and has found 2 corrupt chunks. I will remove them now
