### ISSUE TITLE
Bug: Thru Can Tp You Into Blocks.

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#115]
Sometimes Threw Will Send You Into a 1x1x1 block i think and glitches your head in the block above.
Video: https://gyazo.com/a8919c141e48708ca8165b4e7a9ef492

**Comment by RedDiamondREC** [comment]
basically make sure when you do a /threw its a 1x2x1 area not 1x1x1

**Comment by EvilPeanut** [comment]
Duplicate of #71
