### ISSUE TITLE
Bug: Move Command With Data Issues.

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#119]
Move Command Causes Data Issues and removes data items.
Video: https://gyazo.com/dba75dfc397d9716394d9c7a02b3561f

**Comment by EvilPeanut** [comment]
Isn't this a minecraft command as opposed to an EvilBook command?

**Comment by RedDiamondREC** [comment]
No it would be a imbue in evilbook. Possibly a issue with coping different facing of directions

**Comment by EvilPeanut** [comment]
Duplicate of #131
