### ISSUE TITLE
New Command

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#121]
Add A SetHub Command Where I Can SetHub To A Players Location As Hub. In Console Only.
Example: I can walk to the place i want hub to be set than i go in counsole and type 
/SetHub (Player Name For Location) (Direction) (North,South,East,West) (EX:) /SetHub RedDiamondREC North

**Comment by EvilPeanut** [comment]
The current /hub command sends the player to the spawn point of the main world. This works as intended; I can't see a good use for /sethub
