### ISSUE TITLE
Reset player positions

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#129]
add a command for tycoon and up for:
resetting a players location to /hub (or world's 0,100,0 point or world's /spawn) even if they are offline or online
reason: i get this issue every month when a person logs on it crashes the server due to there location. aka a bugged chunk. ik you can fix the chunks but they always appears. so i need it for taking people out of the bugged location when they are inside of it instead of asking you to do it every time.

**Comment by EvilPeanut** [comment]
I can imagine this would upset alot of the players as they may be in a certain location building and wouldn't remember how to get back if they were reset. Perhaps there is a better solution?

**Comment by RedDiamondREC** [comment]
yes but they crash the server whenever they try to login you can try to make it move them within 5 chunks of where they are or put a message in there /mail of there last location in cords

**Comment by EvilPeanut** [comment]
I'm currently playing around with ways to scan and fix chunks in realtime. If all else fails then I'll do this :)

**Comment by RedDiamondREC** [comment]
Glad to hear

On Nov 19, 2017 12:03 PM, "Reece Lecrivain" <notifications@github.com>
wrote:

I'm currently playing around with ways to scan and fix chunks in realtime.
If all else fails then I'll do this :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EvilPeanut/EvilBook/issues/129#issuecomment-345536611>,
or mute the thread

**Comment by EvilPeanut** [comment]
Crashing should now be fixed; no longer required
