### ISSUE TITLE
Plot Issue

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#137]
Plot Claim Build Area https://gyazo.com/d219264bbd0a127924437f84577464dc
Plot Claim Should Be Area https://gyazo.com/dc355ff4818351c5eb4ed4b27a7f4341
(wood is where people are permitted / should be permitted to use

**Comment by EvilPeanut** [comment]
This isn't a bug, it's a feature. The person's plot includes half of the surrounding road; this is to allow them to build bridges if they own two adjacent plots or even combine two plots.
