### ISSUE TITLE
/Mail Issue

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#178]
![2017-12-23_22 07 48](https://user-images.githubusercontent.com/18478420/34329390-d3e768dc-e8c3-11e7-8c4f-73e04b67d91b.png)
![2017-12-23_22 07 55](https://user-images.githubusercontent.com/18478420/34329391-d4d57734-e8c3-11e7-9c0e-35a1d6650aa0.png)
it shows inventory in /mail

**Comment by EvilPeanut** [comment]
I will investigate, but I do believe this is a feature so you can put mail in to your inventory when you have any 😄

**Comment by EvilPeanut** [comment]
Working as intended, not a bug
