### ISSUE TITLE
Lower Ranks can kick higher ranks

### ISSUE THREAD

**Issue by ghost** [EvilPeanut/EvilBook#188]
So I don't know if you know this already but Lower ranks like Admin can kick the higher ranks even me and I was shocked and here and here is some proof
![_aa808ca433439c5fd138e250c7cd7660-png](https://user-images.githubusercontent.com/32628438/34464200-4b5a1042-ee2b-11e7-8705-719a9ca82d1c.jpg)

**Comment by xXdogopusXx** [comment]
Reece told me earlier that they should be able to do that in the case of an AdminStaff, Tycoon, Investor, etc. Starts abusing. An Admin would be able to stop them in that event.

**Comment by EvilPeanut** [comment]
@xXdogopusXx I can confirm this. If a lower rank abusively bans or kicks then this is punishable with a ban to them
