### ISSUE TITLE
Change plot world plot sizes

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#49]
make all plots 100x100 + reset the world

**Comment by EvilPeanut** [comment]
I don't really want to reset the world and lose the builds currently on it. Also if someone wants more space for a build then they can purchase surrounding plots to make one big plot. @RedDiamondREC What do you think?

**Comment by RedDiamondREC** [comment]
Ya like slept mu tuple plots if u pay for it and than give them like a 9 plots squair
