### ISSUE TITLE
Plotworld issue #2

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#50]
Protect All roads in plot world

**Comment by EvilPeanut** [comment]
Each plot owns half of its surrounding road. What do you mean by protecting all roads?

**Comment by RedDiamondREC** [comment]
yes so you cant edit the roads at all

**Comment by EvilPeanut** [comment]
I considered this initially but decided to allow the plot to own half of its surrounding road so a play can combine two plots they own or create cool things like a bridge over the road between two plots. @raxixor @msmith97 What do you guys think?

**Comment by msmith97** [comment]
I feel like that would be come a problem. Because more than one person would own it and would cause a griefing matter or a fight about it.

**Comment by EvilPeanut** [comment]
Each plot owns half of the surrounding road. Plots don't share any blocks of the road.

**Comment by msmith97** [comment]
That is good

**Comment by RedDiamondREC** [comment]
Perfiect
