### ISSUE TITLE
Add plot sharing to PlotWorld

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#51]
Add Ability to log the plot world

**Comment by EvilPeanut** [comment]
Is this needed? Griefing isn't possible in the plot world

**Comment by RedDiamondREC** [comment]
just so the roads cant be edited everything else is fine

**Comment by raxixor** [comment]
What if someone who was allowed access to the plot griefs? Then it can't be rolled back without logging.

**Comment by RedDiamondREC** [comment]
If people share a plot

**Comment by EvilPeanut** [comment]
Plot sharing isn't possible at the moment is it? If it isn't then we should look at adding this :smile:

**Comment by RedDiamondREC** [comment]
yes I believe this should be added in the near future

**Comment by msmith97** [comment]
I think log should be there just incase of need and we do need to add plot share.

**Comment by EvilPeanut** [comment]
Okay sweet, you guys all happy if I add plot sharing and add log to the plot world?

**Comment by msmith97** [comment]
I am
