### ISSUE TITLE
Plotworld issue #2

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#52]
Amount of plots: YOU PICK
Either

non donating ranks
1 plot
donating ranks
2 plots
Trusted ranks
3 plots

non donating ranks
2 plot
donating ranks
3 plots
Trusted ranks
4 plots

**Comment by EvilPeanut** [comment]
Should we limit the number of plots a person can obtain? Currently each plot has a monetary cost to obtain. I'd prefer to avoid restrictions

**Comment by RedDiamondREC** [comment]
Alright that's fine
