### ISSUE TITLE
A cheating bug for getting free stuff in survival

### ISSUE THREAD

**Issue by msmith97** [EvilPeanut/EvilBook#57]
They /disguise  into a donkey in creative put a chest on it and put whatever they want in the chest and then go into survival.

**Comment by EvilPeanut** [comment]
Maybe we should block /disguise in survival and un-disguise people when they go into survival using a disguise. I think disguise in survival also allows someone to be invincible, this would fix both issues.

**Comment by RedDiamondREC** [comment]
that would be fine

**Comment by msmith97** [comment]
That would be great.
