### ISSUE TITLE
Server is not working

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#58]
the server wont let us log in

**Comment by EvilPeanut** [comment]
Looking in to it now, we will need to find a way to keep it 24/7 and fix the crashing aswell

**Comment by EvilPeanut** [comment]
I have brought the server back up and looked in to the cause. It seems to be an issue with SQL communicating with EvilBook about if a player's profile exists or not

**Comment by RedDiamondREC** [comment]
Alright thank you
