### ISSUE TITLE
ABUSE PROLBLEM DO THIS ASAP!!!

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#60]
SOMEONE HAS BEEN PROMOTING PEOPLE TO SERVERHOST!!. PLEASE BAN THEM AND DEMOTE THEM AND DEMOTE ALL SERVERHOSTS TO ADMIN OR TO WHATEVER THERE RANK THEY WHERE! ACCAPT RedDiamondREC & MatthewSmith17!

**Comment by EvilPeanut** [comment]
This is resolved now, right?

**Comment by RedDiamondREC** [comment]
Ya
