### ISSUE TITLE
All Console Issues Reported Inside Console.

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#64]
‎2‎:‎49‎:‎30‎ ‎PM CONSOLE: 
[INFO] Command 'day' conflicts with plugin 'EvilBook v8.0.4', McMyAdmin will not receive this command. Command will be sent to 'EvilBook v8.0.4' instead.

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: java.lang.IllegalArgumentException: Can not set final java.util.Collection field net.minecraft.server.v1_10_R1.PacketPlayOutScoreboardTeam.h to java.lang.Integer

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(Unknown Source)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at java.lang.reflect.Field.set(Unknown Source)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at com.amentrix.evilbook.nametag.PacketPlayOut.setField(PacketPlayOut.java:58)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at com.amentrix.evilbook.nametag.PacketPlayOut.<init>(PacketPlayOut.java:22)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at com.amentrix.evilbook.nametag.NametagManager.sendPacketsAddTeam(NametagManager.java:237)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at com.amentrix.evilbook.nametag.NametagManager.register(NametagManager.java:35)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at com.amentrix.evilbook.nametag.NametagManager.declareTeam(NametagManager.java:153)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at com.amentrix.evilbook.nametag.NametagManager.get(NametagManager.java:174)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at com.amentrix.evilbook.nametag.NametagManager.overlap(NametagManager.java:131)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at com.amentrix.evilbook.main.PlayerProfile$1.run(PlayerProfile.java:86)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
WARN]: at java.lang.Thread.run(Unknown Source)

‎2‎:‎37‎:‎13‎ ‎PM CONSOLE: 
[INFO] Failed to send packet for player (Packet209SetScoreboardTeam) :

**Comment by EvilPeanut** [comment]
The command conflict isn't an issue. The leader board errors are however, I'll have a look in to this.

**Comment by RedDiamondREC** [comment]
Alright ty

**Comment by EvilPeanut** [comment]
@RedDiamondREC I have just released an update which fixes this error :smiley: it also fixes the player's nametags to be coloured again (The console spam was caused by this failing)
