### ISSUE TITLE
Corrupt chunks causing crashes

### ISSUE THREAD

**Issue by RedDiamondREC** [EvilPeanut/EvilBook#92]
https://gyazo.com/d0b16d87f01b8e50c0e17379b09e9ef1

**Comment by EvilPeanut** [comment]
Is the crashing fixed? I found and fixed the corrupt chunks in Flatland which I believed to be the cause. However if there is still crashing then I'll check all of the other worlds for corrupt chunks which may be causing the crashing if it's not fixed :smile:

**Comment by RedDiamondREC** [comment]
GREAT JOB
:D
