### ISSUE TITLE
Add More Colors

### ISSUE THREAD

**Issue by msmith97** [EvilPeanut/EvilBook#95]
You should add more colors to /colors, Like: Pink, Brown, Orange, Tan, Sliver.

**Comment by EvilPeanut** [comment]
We can only support the colors which Minecraft itself supports. Does minecraft support these colors?

**Comment by msmith97** [comment]
I have no clue, honestly.

**Comment by EvilPeanut** [comment]
After research, Minecraft doesn't appear to support any more colors which aren't already supported by EvilBook. 😄
